version: '2'

services:
  filters:
    environment:
      - HTTP_PROXY=http://192.168.56.1:7890
      - HTTPS_PROXY=http://192.168.56.1:7890
      - NO_PROXY=localhost,127.0.0.1

  matecat:
    environment:
      - HTTP_PROXY=http://192.168.56.1:7890
      - HTTPS_PROXY=http://192.168.56.1:7890
      - NO_PROXY=localhost,127.0.0.1

  mosesdecoder:
    environment:
      - HTTP_PROXY=http://192.168.56.1:7890
      - HTTPS_PROXY=http://192.168.56.1:7890
      - NO_PROXY=localhost,127.0.0.1 